In [1]:
import pandas as pd
from datetime import datetime

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [106]:
df_aapl = pd.read_csv('drive/My Drive/thesis/dataset/data123.csv')

In [107]:
df_aapl

,Date,Open,High,Low,Close,Adj Close,Volume,macd,Unnamed: 8,12,Unnamed: 10,26,Unnamed: 12,Unnamed: 13
0,2021/8/24,149.449997,150.860001,149.149994,149.619995,148.313415,48606400,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
1,2021/8/25,149.809998,150.320007,147.800003,148.360001,147.064423,58991300,-0.100512,NaN,NaN,NaN,NaN,NaN,NaN
2,2021/8/26,148.350006,149.119995,147.509995,147.539993,146.251556,48597200,-0.243530,NaN,NaN,NaN,NaN,NaN,NaN
3,2021/8/27,147.479996,148.750000,146.830002,148.600006,147.302322,55802400,-0.268246,NaN,NaN,NaN,NaN,NaN,NaN
4,2021/8/30,149.000000,153.490005,148.610001,153.119995,151.782852,90956700,0.076016,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
337,2022/12/23,130.919998,132.419998,129.639999,131.860001,131.658981,63814900,-3.670694,NaN,NaN,NaN,NaN,NaN,NaN
338,2022/12/27,131.380005,131.410004,128.720001,130.029999,129.831772,69007800,-3.936230,NaN,NaN,NaN,NaN,NaN,NaN
339,2022/12/28,129.669998,131.029999,125.870003,126.040001,125.847855,85438400,-4.417705,NaN,NaN,NaN,NaN,NaN,NaN
340,2022/12/29,127.989998,130.479996,127.730003,129.610001,129.412415,75703700,-4.459798,NaN,NaN,NaN,NaN,NaN,NaN
341,2022/12/30,128.410004,129.949997,127.430000,129.929993,129.731918,76960600,-4.416427,NaN,NaN,NaN,NaN,NaN,NaN

In [108]:
df_aapl = df_aapl.drop(df_aapl.columns[[7,8,9,10,11,12,13]], axis=1)

In [109]:
ema_12 = df_aapl["Close"].ewm(span=12, adjust=False).mean()
ema_26 = df_aapl["Close"].ewm(span=26, adjust=False).mean()
macd = ema_12 - ema_26
signal = macd.ewm(span=9, adjust=False).mean()
# Calculate the histogram
hist = macd - signal
df_aapl['macd'] = hist

In [110]:
df_aapl

,Date,Open,High,Low,Close,Adj Close,Volume,macd
0,2021/8/24,149.449997,150.860001,149.149994,149.619995,148.313415,48606400,0.000000
1,2021/8/25,149.809998,150.320007,147.800003,148.360001,147.064423,58991300,-0.080410
2,2021/8/26,148.350006,149.119995,147.509995,147.539993,146.251556,48597200,-0.178742
3,2021/8/27,147.479996,148.750000,146.830002,148.600006,147.302322,55802400,-0.162766
4,2021/8/30,149.000000,153.490005,148.610001,153.119995,151.782852,90956700,0.145196
...,...,...,...,...,...,...,...,...
337,2022/12/23,130.919998,132.419998,129.639999,131.860001,131.658981,63814900,-1.100532
338,2022/12/27,131.380005,131.410004,128.720001,130.029999,129.831772,69007800,-1.092855
339,2022/12/28,129.669998,131.029999,125.870003,126.040001,125.847855,85438400,-1.259464
340,2022/12/29,127.989998,130.479996,127.730003,129.610001,129.412415,75703700,-1.041245
341,2022/12/30,128.410004,129.949997,127.430000,129.929993,129.731918,76960600,-0.798299

In [111]:
df_aapl['Date'] = pd.to_datetime(df_aapl['Date']).dt.date

In [112]:
# convert string '2022-03*-01' to datetime.date object
date_str = '2022-03-01'
date = datetime.strptime(date_str, '%Y-%m-%d').date()

In [113]:
df_aapl_final = df_aapl[df_aapl['Date'] >= date].copy()

In [114]:
df_aapl_final['stock_symbol'] = 'AAPL'

In [115]:
df_aapl_final = df_aapl_final[['stock_symbol','Date','Open','Close','High','Low','Volume','macd']]

In [116]:
df_aapl_final

,stock_symbol,Date,Open,Close,High,Low,Volume,macd
130,AAPL,2022-03-01,164.699997,163.199997,166.600006,161.970001,83474400,-0.760515
131,AAPL,2022-03-02,164.389999,166.559998,167.360001,162.949997,79724800,-0.470632
132,AAPL,2022-03-03,168.470001,166.229996,168.910004,165.550003,76678400,-0.274369
133,AAPL,2022-03-04,164.490005,163.169998,165.550003,162.100006,83737200,-0.320668
134,AAPL,2022-03-07,163.360001,159.300003,165.020004,159.039993,96418800,-0.567536
...,...,...,...,...,...,...,...,...
337,AAPL,2022-12-23,130.919998,131.860001,132.419998,129.639999,63814900,-1.100532
338,AAPL,2022-12-27,131.380005,130.029999,131.410004,128.720001,69007800,-1.092855
339,AAPL,2022-12-28,129.669998,126.040001,131.029999,125.870003,85438400,-1.259464
340,AAPL,2022-12-29,127.989998,129.610001,130.479996,127.730003,75703700,-1.041245
341,AAPL,2022-12-30,128.410004,129.929993,129.949997,127.430000,76960600,-0.798299

In [117]:
df_all = pd.read_csv('drive/My Drive/thesis/dataset/all_stock_price [final].csv')

In [118]:
df_all = df_all.rename(columns={'symbol': 'stock_symbol'})

In [119]:
df_all = df_all[['stock_symbol','Date','Open','Close','High','Low','Volume','macd']]

In [120]:
df_all = df_all.sort_values(['stock_symbol', 'Date'])

In [121]:
df_all

,stock_symbol,Date,Open,Close,High,Low,Volume,macd
424,AMGN,2022-03-01,225.279999,225.210007,227.789993,223.740005,4573500,-0.103738
425,AMGN,2022-03-02,225.039993,228.589996,230.399994,224.649994,3387200,0.217628
426,AMGN,2022-03-03,230.880005,232.639999,234.270004,230.009995,3638400,0.670710
427,AMGN,2022-03-04,230.699997,232.910004,235.740005,230.139999,3764400,0.939837
428,AMGN,2022-03-07,231.289993,234.360001,239.660004,231.229996,3713200,1.152719
...,...,...,...,...,...,...,...,...
6143,WMT,2022-12-23,143.050003,143.770004,143.800003,142.279999,3182500,-0.884780
6144,WMT,2022-12-27,144.039993,143.809998,144.449997,143.190002,3348200,-0.770568
6145,WMT,2022-12-28,143.470001,141.289993,143.669998,140.910004,5082100,-0.819899
6146,WMT,2022-12-29,142.139999,142.149994,143.020004,141.750000,3057300,-0.751577
6147,WMT,2022-12-30,141.559998,141.789993,141.990005,140.809998,3835300,-0.689238

In [122]:
df_all['Date'] = pd.to_datetime(df_all['Date']).dt.date

In [123]:
# convert string '2022-03*-01' to datetime.date object
date_str = '2022-03-01'
date = datetime.strptime(date_str, '%Y-%m-%d').date()

In [124]:
df_all_final = df_all[df_all['Date'] >= date].copy()

In [125]:
df_all_final = df_all_final[df_all_final.stock_symbol != 'MRK']

In [126]:
df_all_final

,stock_symbol,Date,Open,Close,High,Low,Volume,macd
424,AMGN,2022-03-01,225.279999,225.210007,227.789993,223.740005,4573500,-0.103738
425,AMGN,2022-03-02,225.039993,228.589996,230.399994,224.649994,3387200,0.217628
426,AMGN,2022-03-03,230.880005,232.639999,234.270004,230.009995,3638400,0.670710
427,AMGN,2022-03-04,230.699997,232.910004,235.740005,230.139999,3764400,0.939837
428,AMGN,2022-03-07,231.289993,234.360001,239.660004,231.229996,3713200,1.152719
...,...,...,...,...,...,...,...,...
6143,WMT,2022-12-23,143.050003,143.770004,143.800003,142.279999,3182500,-0.884780
6144,WMT,2022-12-27,144.039993,143.809998,144.449997,143.190002,3348200,-0.770568
6145,WMT,2022-12-28,143.470001,141.289993,143.669998,140.910004,5082100,-0.819899
6146,WMT,2022-12-29,142.139999,142.149994,143.020004,141.750000,3057300,-0.751577
6147,WMT,2022-12-30,141.559998,141.789993,141.990005,140.809998,3835300,-0.689238

In [127]:
df_macd = pd.concat([df_aapl_final,df_all_final], axis=0)

In [128]:
df_macd = df_macd[['stock_symbol','Date','macd']]

In [129]:
df_macd

     stock_symbol        Date      macd
130          AAPL  2022-03-01 -0.760515
131          AAPL  2022-03-02 -0.470632
132          AAPL  2022-03-03 -0.274369
133          AAPL  2022-03-04 -0.320668
134          AAPL  2022-03-07 -0.567536
...           ...         ...       ...
6143          WMT  2022-12-23 -0.884780
6144          WMT  2022-12-27 -0.770568
6145          WMT  2022-12-28 -0.819899
6146          WMT  2022-12-29 -0.751577
6147          WMT  2022-12-30 -0.689238

[6148 rows x 3 columns]

# Update tweet

In [130]:
df_tweets = pd.read_csv('drive/My Drive/thesis/dataset/All_tweets_with_sentiment_new[this one].csv',lineterminator='\n')

In [131]:
df_tweets

,Unnamed: 0,id,date,rawContent,stock_symbol,unique_cashtags,text_preprocess_withemo,sentiment_prediction
0,2,1608968680104423426,2022-12-30 23:30:01+00:00,Nice print for $KO Size: 1968137 Price: 63.61 ...,KO,1,nice print for $ko size: 1968137 price: 63.61 ...,2
1,4,1608965938690285570,2022-12-30 23:19:07+00:00,$KO new alert at https://t.co/A7qrDarJHY #st...,KO,1,$ko new alert at #stocks #daytrading #nyse #na...,1
2,5,1608965461320040460,2022-12-30 23:17:13+00:00,$KO - Coca-Cola: 61st Consecutive Annual Divid...,KO,1,$ko - coca-cola: 61st consecutive annual divid...,2
3,6,1608965056234127367,2022-12-30 23:15:37+00:00,Are the implications of this good or bad in a ...,KO,1,are the implications of this good or bad in a ...,0
4,11,1608942180604968961,2022-12-30 21:44:43+00:00,"$KO ""Top analyst price target for next week\nh...",KO,1,"$ko ""top analyst price target for next week",2
...,...,...,...,...,...,...,...,...
621566,19741,1488424257134919685,2022-02-01 08:09:31+00:00,"$WBA~Utilizing our stock and option alerts, ad...",WBA,1,"$wba~utilizing our stock and option alerts, ad...",1
621567,19743,1488362308241866753,2022-02-01 04:03:21+00:00,$WBA:\n\nNew Insider Filing on Walgreens Boots...,WBA,1,$wba:\n\nnew insider filing on walgreens boots...,1
621568,19744,1488351007490945026,2022-02-01 03:18:27+00:00,$WBA:\n\nNew Insider Filing on Walgreens Boots...,WBA,1,$wba:\n\nnew insider filing on walgreens boots...,1
621569,19746,1488336565151715328,2022-02-01 02:21:03+00:00,Stock: $WBA - \n*** REALTIME TREND ***\nSELL\n...,WBA,1,stock: $wba - \n*** realtime trend ***\nsell\n...,2
621570,19747,1488325040076558337,2022-02-01 01:35:15+00:00,If yâ€™all got into $WBA I still think itâ€™ll ope...,WBA,1,if yâ€™all got into $wba i still think itâ€™ll ope...,2

In [132]:
df_tweets = df_tweets[df_tweets.rawContent.str.contains('analyst') != True].copy()
df_tweets.shape

(526394, 8)

In [133]:
df_tweet1 = df_tweets[['date','rawContent','text_preprocess_withemo','sentiment_prediction','stock_symbol']].copy()

In [134]:
# convert the 'datetime' column to a datetime dtype
df_tweet1['date'] = pd.to_datetime(df_tweet1['date'])

# apply the date transformation based on the time
df_tweet1['Date'] = df_tweet1['date'].apply(lambda x: x.date() if x.time() >= pd.to_datetime('09:30:00').time() else (x.date() + pd.Timedelta(days=-1)))

# print the resulting dataframe
df_tweet1

,date,rawContent,text_preprocess_withemo,sentiment_prediction,stock_symbol,Date
0,2022-12-30 23:30:01+00:00,Nice print for $KO Size: 1968137 Price: 63.61 ...,nice print for $ko size: 1968137 price: 63.61 ...,2,KO,2022-12-30
1,2022-12-30 23:19:07+00:00,$KO new alert at https://t.co/A7qrDarJHY #st...,$ko new alert at #stocks #daytrading #nyse #na...,1,KO,2022-12-30
2,2022-12-30 23:17:13+00:00,$KO - Coca-Cola: 61st Consecutive Annual Divid...,$ko - coca-cola: 61st consecutive annual divid...,2,KO,2022-12-30
3,2022-12-30 23:15:37+00:00,Are the implications of this good or bad in a ...,are the implications of this good or bad in a ...,0,KO,2022-12-30
5,2022-12-30 21:21:15+00:00,$KO Below Avg Volume\nDaily appearances since ...,$ko below avg volume\ndaily appearances since ...,0,KO,2022-12-30
...,...,...,...,...,...,...
621566,2022-02-01 08:09:31+00:00,"$WBA~Utilizing our stock and option alerts, ad...","$wba~utilizing our stock and option alerts, ad...",1,WBA,2022-01-31
621567,2022-02-01 04:03:21+00:00,$WBA:\n\nNew Insider Filing on Walgreens Boots...,$wba:\n\nnew insider filing on walgreens boots...,1,WBA,2022-01-31
621568,2022-02-01 03:18:27+00:00,$WBA:\n\nNew Insider Filing on Walgreens Boots...,$wba:\n\nnew insider filing on walgreens boots...,1,WBA,2022-01-31
621569,2022-02-01 02:21:03+00:00,Stock: $WBA - \n*** REALTIME TREND ***\nSELL\n...,stock: $wba - \n*** realtime trend ***\nsell\n...,2,WBA,2022-01-31
621570,2022-02-01 01:35:15+00:00,If yâ€™all got into $WBA I still think itâ€™ll ope...,if yâ€™all got into $wba i still think itâ€™ll ope...,2,WBA,2022-01-31

In [135]:
df_tweet2 = df_tweet1[['Date','rawContent','text_preprocess_withemo','sentiment_prediction','stock_symbol']].copy()
df_tweet2

,Date,rawContent,text_preprocess_withemo,sentiment_prediction,stock_symbol
0,2022-12-30,Nice print for $KO Size: 1968137 Price: 63.61 ...,nice print for $ko size: 1968137 price: 63.61 ...,2,KO
1,2022-12-30,$KO new alert at https://t.co/A7qrDarJHY #st...,$ko new alert at #stocks #daytrading #nyse #na...,1,KO
2,2022-12-30,$KO - Coca-Cola: 61st Consecutive Annual Divid...,$ko - coca-cola: 61st consecutive annual divid...,2,KO
3,2022-12-30,Are the implications of this good or bad in a ...,are the implications of this good or bad in a ...,0,KO
5,2022-12-30,$KO Below Avg Volume\nDaily appearances since ...,$ko below avg volume\ndaily appearances since ...,0,KO
...,...,...,...,...,...
621566,2022-01-31,"$WBA~Utilizing our stock and option alerts, ad...","$wba~utilizing our stock and option alerts, ad...",1,WBA
621567,2022-01-31,$WBA:\n\nNew Insider Filing on Walgreens Boots...,$wba:\n\nnew insider filing on walgreens boots...,1,WBA
621568,2022-01-31,$WBA:\n\nNew Insider Filing on Walgreens Boots...,$wba:\n\nnew insider filing on walgreens boots...,1,WBA
621569,2022-01-31,Stock: $WBA - \n*** REALTIME TREND ***\nSELL\n...,stock: $wba - \n*** realtime trend ***\nsell\n...,2,WBA
621570,2022-01-31,If yâ€™all got into $WBA I still think itâ€™ll ope...,if yâ€™all got into $wba i still think itâ€™ll ope...,2,WBA

In [136]:
# convert date_column to datetime
#df_tweet1['date'] = pd.to_datetime(df_tweet1['date']).dt.date

# sort the dataframe by the date_column in ascending order
df_tweet2.sort_values(by='Date', inplace=True)

In [137]:
df_tweet2 = df_tweet2.reset_index(drop=True)

In [138]:
df_tweet2

,Date,rawContent,text_preprocess_withemo,sentiment_prediction,stock_symbol
0,2022-01-31,If yâ€™all got into $WBA I still think itâ€™ll ope...,if yâ€™all got into $wba i still think itâ€™ll ope...,2,WBA
1,2022-01-31,$MSFT - FTC to handle review of Microsoft's de...,$msft - ftc to handle review of microsoft's de...,1,MSFT
2,2022-01-31,I was in $MSFT all day...I knew it was going t...,i was in $msft all day...i knew it was going t...,2,MSFT
3,2022-01-31,$IBM International Business Machines Corporati...,$ibm international business machines corporati...,2,IBM
4,2022-01-31,Stock: $IBM - \n*** REALTIME TREND ***\nSELL\n...,stock: $ibm - \n*** realtime trend ***\nsell\n...,2,IBM
...,...,...,...,...,...
526389,2022-12-30,$JPM Strike: 120.00 Expiration: 2023-03-17 Put...,$jpm strike: 120.00 expiration: 2023-03-17 put...,1,JPM
526390,2022-12-30,$JPM Strike: 150.00 Expiration: 2023-03-17 Cal...,$jpm strike: 150.00 expiration: 2023-03-17 cal...,1,JPM
526391,2022-12-30,$jpm Don't miss the next move in a few hours....,$jpm don't miss the next move in a few hours.~,1,JPM
526392,2022-12-30,""" $JPM and its employees had actual knowledge ...",""" $jpm and its employees had actual knowledge ...",0,JPM
526393,2022-12-30,Nice print for $KO Size: 1968137 Price: 63.61 ...,nice print for $ko size: 1968137 price: 63.61 ...,2,KO

In [139]:
# convert string '2022-03*-01' to datetime.date object
date_str = '2022-03-01'
date = datetime.strptime(date_str, '%Y-%m-%d').date()

In [140]:
df_tweet_final = df_tweet2[df_tweet2['Date'] >= date]

In [141]:
df_tweet_final = df_tweet_final[df_tweet_final.stock_symbol != 'MRK']

In [142]:
df_tweet_final

,Date,rawContent,text_preprocess_withemo,sentiment_prediction,stock_symbol
40296,2022-03-01,$INTC getting love!,$intc getting love!,2,INTC
40297,2022-03-01,$INTC calls ðŸ¤” #StateOfTheUnion,$intc calls ðŸ¤” #stateoftheunion,1,INTC
40298,2022-03-01,Woop $INTC mentioned. Yup hubby is a high up a...,woop $intc mentioned. yup hubby is a high up a...,2,INTC
40299,2022-03-01,$INTC gets a BIG shoutout.,$intc gets a big shoutout.,2,INTC
40300,2022-03-01,$INTC BULLISH???????,$intc bullish???????,2,INTC
...,...,...,...,...,...
526389,2022-12-30,$JPM Strike: 120.00 Expiration: 2023-03-17 Put...,$jpm strike: 120.00 expiration: 2023-03-17 put...,1,JPM
526390,2022-12-30,$JPM Strike: 150.00 Expiration: 2023-03-17 Cal...,$jpm strike: 150.00 expiration: 2023-03-17 cal...,1,JPM
526391,2022-12-30,$jpm Don't miss the next move in a few hours....,$jpm don't miss the next move in a few hours.~,1,JPM
526392,2022-12-30,""" $JPM and its employees had actual knowledge ...",""" $jpm and its employees had actual knowledge ...",0,JPM
526393,2022-12-30,Nice print for $KO Size: 1968137 Price: 63.61 ...,nice print for $ko size: 1968137 price: 63.61 ...,2,KO

In [143]:
# group by date and calculate count and mean of sentiment
result = df_tweet_final.groupby(['stock_symbol','Date'])['sentiment_prediction'].value_counts().unstack(fill_value=0)

# calculate the mean sentiment for each date
result['sentiment_mean'] = df_tweet_final.groupby(['stock_symbol','Date'])['sentiment_prediction'].mean()

# rename columns
result.columns = ['tweet_sentiment_count_0', 'tweet_sentiment_count_1', 'tweet_sentiment_count_2', 'tweet_sentiment_mean']

# print the result
result

                         tweet_sentiment_count_0  tweet_sentiment_count_1  \
stock_symbol Date
AMGN         2022-03-01                        2                        7
             2022-03-02                        0                       11
             2022-03-03                        2                        8
             2022-03-04                        1                        7
             2022-03-05                        0                        8
...                                          ...                      ...
WMT          2022-12-26                        6                       21
             2022-12-27                       19                       25
             2022-12-28                       16                       24
             2022-12-29                       11                       20
             2022-12-30                        8                       16

                         tweet_sentiment_count_2  tweet_sentiment_mean
stock_symbol Date
AMGN         2022-03-01                       16              1.560000
             2022-03-02                       12              1.521739
             2022-03-03                       19              1.586207
             2022-03-04                        6              1.357143
             2022-03-05                        9              1.529412
...                                          ...                   ...
WMT          2022-12-26                       28              1.400000
             2022-12-27                       32              1.171053
             2022-12-28                       40              1.300000
             2022-12-29                       35              1.363636
             2022-12-30                       20              1.272727

[8540 rows x 4 columns]

In [144]:
result = result.reset_index(drop=False)

In [145]:
#result = result.rename(columns={'date': 'Date'})

In [146]:
result

,stock_symbol,Date,tweet_sentiment_count_0,tweet_sentiment_count_1,tweet_sentiment_count_2,tweet_sentiment_mean
0,AMGN,2022-03-01,2,7,16,1.560000
1,AMGN,2022-03-02,0,11,12,1.521739
2,AMGN,2022-03-03,2,8,19,1.586207
3,AMGN,2022-03-04,1,7,6,1.357143
4,AMGN,2022-03-05,0,8,9,1.529412
...,...,...,...,...,...,...
8535,WMT,2022-12-26,6,21,28,1.400000
8536,WMT,2022-12-27,19,25,32,1.171053
8537,WMT,2022-12-28,16,24,40,1.300000
8538,WMT,2022-12-29,11,20,35,1.363636
8539,WMT,2022-12-30,8,16,20,1.272727

In [147]:
result["stock_symbol"] = result["stock_symbol"].str.replace("VISA", "V")

In [170]:
df_1 = pd.read_csv('drive/My Drive/thesis/dataset/final_dataset_with_all_stock.csv')

In [171]:
df_1 = df_1.drop(df_1.columns[0],axis=1)

In [172]:
#df_1

In [173]:
df_1 = df_1.sort_values(by=['stock_symbol', 'Date'])

In [174]:
df_1

,stock_symbol,Date,Open,Close,High,Low,Volume,macd,tweet_sentiment_count_0,tweet_sentiment_count_1,...,news_sentiment_count_1,news_sentiment_count_2,news_sentiment_mean,trends,Null_value_news,Null_value_stocktwit,week_day,Thursday,Tuesday,Wednesday
3668,AAPL,2022-03-01,164.699997,163.199997,166.600006,161.970001,83474400,-1.845011,164,125,...,1.0,0.0,0.333333,27,0,0,Tuesday,0,1,0
3669,AAPL,2022-03-02,164.389999,166.559998,167.360001,162.949997,79724800,-1.672787,69,200,...,0.0,0.0,0.000000,30,0,0,Wednesday,0,0,1
3670,AAPL,2022-03-03,168.470001,166.229996,168.910004,165.550003,76678400,-1.545115,103,160,...,2.0,0.0,1.000000,28,0,0,Thursday,1,0,0
3671,AAPL,2022-03-08,158.820007,157.440002,162.880005,155.800003,131148300,-2.489808,158,503,...,38.0,8.0,1.148936,37,0,0,Tuesday,0,1,0
3672,AAPL,2022-03-09,161.479996,162.949997,163.410004,159.410004,91454900,-2.358373,84,224,...,28.0,8.0,1.222222,33,0,0,Wednesday,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3663,WMT,2022-12-21,144.320007,145.179993,145.940002,144.259995,4575500,-0.342863,14,23,...,12.0,3.0,1.000000,21,0,0,Wednesday,0,0,1
3664,WMT,2022-12-22,144.770004,143.479996,144.979996,141.929993,4360800,-0.524842,9,33,...,14.0,3.0,1.111111,17,0,0,Thursday,1,0,0
3665,WMT,2022-12-27,144.039993,143.809998,144.449997,143.190002,3348200,-0.716733,19,25,...,5.0,5.0,1.250000,16,0,0,Tuesday,0,1,0
3666,WMT,2022-12-28,143.470001,141.289993,143.669998,140.910004,5082100,-0.971038,16,24,...,5.0,3.0,1.222222,17,0,0,Wednesday,0,0,1
3667,WMT,2022-12-29,142.139999,142.149994,143.020004,141.750000,3057300,-1.090610,11,20,...,3.0,2.0,1.400000,17,0,0,Thursday,1,0,0

In [175]:
df_1['Date'] = pd.to_datetime(df_1['Date']).dt.date

In [176]:
df_2 = df_1[df_1.stock_symbol == 'AAPL'].copy()

In [177]:
df_3 = df_1[df_1.stock_symbol != 'AAPL'].copy()

In [178]:
df_2 = df_2.drop(df_2[['macd']],axis=1)

In [179]:
df_2.columns

Index(['stock_symbol', 'Date', 'Open', 'Close', 'High', 'Low', 'Volume',
       'tweet_sentiment_count_0', 'tweet_sentiment_count_1',
       'tweet_sentiment_count_2', 'tweet_sentiment_mean',
       'stocktwit_sentiment_count_0', 'stocktwit_sentiment_count_1',
       'stocktwit_sentiment_mean', 'news_sentiment_count_0',
       'news_sentiment_count_1', 'news_sentiment_count_2',
       'news_sentiment_mean', 'trends', 'Null_value_news',
       'Null_value_stocktwit', 'week_day', 'Thursday', 'Tuesday', 'Wednesday'],
      dtype='object')

In [180]:
df_3 = df_3.drop(df_3[['macd','tweet_sentiment_count_0', 'tweet_sentiment_count_1',
       'tweet_sentiment_count_2', 'tweet_sentiment_mean']],axis=1)

In [181]:
df_3.columns

Index(['stock_symbol', 'Date', 'Open', 'Close', 'High', 'Low', 'Volume',
       'stocktwit_sentiment_count_0', 'stocktwit_sentiment_count_1',
       'stocktwit_sentiment_mean', 'news_sentiment_count_0',
       'news_sentiment_count_1', 'news_sentiment_count_2',
       'news_sentiment_mean', 'trends', 'Null_value_news',
       'Null_value_stocktwit', 'week_day', 'Thursday', 'Tuesday', 'Wednesday'],
      dtype='object')

In [190]:
# merge DataFrames on 'stock_symbol' and 'Date' columns
final_dataset_2 = df_2.merge(df_macd, on=['stock_symbol', 'Date'], how='left')

final_dataset_2 = final_dataset_2[['stock_symbol', 'Date', 'Open', 'Close', 'High', 'Low', 'Volume', 'macd',
       'tweet_sentiment_count_0', 'tweet_sentiment_count_1',
       'tweet_sentiment_count_2', 'tweet_sentiment_mean',
       'stocktwit_sentiment_count_0', 'stocktwit_sentiment_count_1',
       'stocktwit_sentiment_mean', 'news_sentiment_count_0',
       'news_sentiment_count_1', 'news_sentiment_count_2',
       'news_sentiment_mean', 'trends', 'Null_value_news',
       'Null_value_stocktwit', 'week_day', 'Thursday', 'Tuesday', 'Wednesday']]

# print the resulting concatenated dataframe
final_dataset_2

,stock_symbol,Date,Open,Close,High,Low,Volume,macd,tweet_sentiment_count_0,tweet_sentiment_count_1,...,news_sentiment_count_1,news_sentiment_count_2,news_sentiment_mean,trends,Null_value_news,Null_value_stocktwit,week_day,Thursday,Tuesday,Wednesday
0,AAPL,2022-03-01,164.699997,163.199997,166.600006,161.970001,83474400,-0.760515,164,125,...,1.0,0.0,0.333333,27,0,0,Tuesday,0,1,0
1,AAPL,2022-03-02,164.389999,166.559998,167.360001,162.949997,79724800,-0.470632,69,200,...,0.0,0.0,0.000000,30,0,0,Wednesday,0,0,1
2,AAPL,2022-03-03,168.470001,166.229996,168.910004,165.550003,76678400,-0.274369,103,160,...,2.0,0.0,1.000000,28,0,0,Thursday,1,0,0
3,AAPL,2022-03-08,158.820007,157.440002,162.880005,155.800003,131148300,-0.797608,158,503,...,38.0,8.0,1.148936,37,0,0,Tuesday,0,1,0
4,AAPL,2022-03-09,161.479996,162.949997,163.410004,159.410004,91454900,-0.532939,84,224,...,28.0,8.0,1.222222,33,0,0,Wednesday,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126,AAPL,2022-12-21,132.979996,135.449997,136.809998,132.750000,85928000,-1.186464,139,217,...,17.0,4.0,1.136364,31,0,0,Wednesday,0,0,1
127,AAPL,2022-12-22,134.350006,132.229996,134.559998,130.300003,77852100,-1.169680,203,244,...,25.0,1.0,1.038462,27,0,0,Thursday,1,0,0
128,AAPL,2022-12-27,131.380005,130.029999,131.410004,128.720001,69007800,-1.092855,357,217,...,15.0,5.0,1.041667,31,0,0,Tuesday,0,1,0
129,AAPL,2022-12-28,129.669998,126.040001,131.029999,125.870003,85438400,-1.259464,580,346,...,21.0,4.0,0.966667,31,0,0,Wednesday,0,0,1
130,AAPL,2022-12-29,127.989998,129.610001,130.479996,127.730003,75703700,-1.041245,182,178,...,22.0,8.0,1.225806,34,0,0,Thursday,1,0,0

In [191]:
# merge DataFrames on 'stock_symbol' and 'Date' columns
final_dataset_3 = df_3.merge(df_macd, on=['stock_symbol', 'Date'], how='left')
final_dataset_3 = final_dataset_3.merge(result, on=['stock_symbol', 'Date'], how='left')


final_dataset_3 = final_dataset_3[['stock_symbol', 'Date', 'Open', 'Close', 'High', 'Low', 'Volume', 'macd',
       'tweet_sentiment_count_0', 'tweet_sentiment_count_1',
       'tweet_sentiment_count_2', 'tweet_sentiment_mean',
       'stocktwit_sentiment_count_0', 'stocktwit_sentiment_count_1',
       'stocktwit_sentiment_mean', 'news_sentiment_count_0',
       'news_sentiment_count_1', 'news_sentiment_count_2',
       'news_sentiment_mean', 'trends', 'Null_value_news',
       'Null_value_stocktwit', 'week_day', 'Thursday', 'Tuesday', 'Wednesday']]

# print the resulting concatenated dataframe
final_dataset_3

,stock_symbol,Date,Open,Close,High,Low,Volume,macd,tweet_sentiment_count_0,tweet_sentiment_count_1,...,news_sentiment_count_1,news_sentiment_count_2,news_sentiment_mean,trends,Null_value_news,Null_value_stocktwit,week_day,Thursday,Tuesday,Wednesday
0,AMGN,2022-03-01,225.279999,225.210007,227.789993,223.740005,4573500,-0.103738,2,7,...,0.0,0.0,1.000000,15,1,0,Tuesday,0,1,0
1,AMGN,2022-03-02,225.039993,228.589996,230.399994,224.649994,3387200,0.217628,0,11,...,0.0,0.0,1.000000,0,1,0,Wednesday,0,0,1
2,AMGN,2022-03-03,230.880005,232.639999,234.270004,230.009995,3638400,0.670710,2,8,...,0.0,0.0,1.000000,42,1,0,Thursday,1,0,0
3,AMGN,2022-03-08,233.860001,231.100006,236.880005,230.559998,2974900,1.015980,2,12,...,3.0,1.0,1.250000,24,0,0,Tuesday,0,1,0
4,AMGN,2022-03-09,234.229996,231.460007,234.529999,230.429993,2640900,0.895978,2,3,...,2.0,1.0,1.000000,32,0,0,Wednesday,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3663,WMT,2022-12-21,144.320007,145.179993,145.940002,144.259995,4575500,-1.058663,14,23,...,12.0,3.0,1.000000,21,0,0,Wednesday,0,0,1
3664,WMT,2022-12-22,144.770004,143.479996,144.979996,141.929993,4360800,-0.992514,9,33,...,14.0,3.0,1.111111,17,0,0,Thursday,1,0,0
3665,WMT,2022-12-27,144.039993,143.809998,144.449997,143.190002,3348200,-0.770568,19,25,...,5.0,5.0,1.250000,16,0,0,Tuesday,0,1,0
3666,WMT,2022-12-28,143.470001,141.289993,143.669998,140.910004,5082100,-0.819899,16,24,...,5.0,3.0,1.222222,17,0,0,Wednesday,0,0,1
3667,WMT,2022-12-29,142.139999,142.149994,143.020004,141.750000,3057300,-0.751577,11,20,...,3.0,2.0,1.400000,17,0,0,Thursday,1,0,0

In [192]:
df_final = pd.concat([final_dataset_2,final_dataset_3],axis=0)

In [193]:
df_final

,stock_symbol,Date,Open,Close,High,Low,Volume,macd,tweet_sentiment_count_0,tweet_sentiment_count_1,...,news_sentiment_count_1,news_sentiment_count_2,news_sentiment_mean,trends,Null_value_news,Null_value_stocktwit,week_day,Thursday,Tuesday,Wednesday
0,AAPL,2022-03-01,164.699997,163.199997,166.600006,161.970001,83474400,-0.760515,164,125,...,1.0,0.0,0.333333,27,0,0,Tuesday,0,1,0
1,AAPL,2022-03-02,164.389999,166.559998,167.360001,162.949997,79724800,-0.470632,69,200,...,0.0,0.0,0.000000,30,0,0,Wednesday,0,0,1
2,AAPL,2022-03-03,168.470001,166.229996,168.910004,165.550003,76678400,-0.274369,103,160,...,2.0,0.0,1.000000,28,0,0,Thursday,1,0,0
3,AAPL,2022-03-08,158.820007,157.440002,162.880005,155.800003,131148300,-0.797608,158,503,...,38.0,8.0,1.148936,37,0,0,Tuesday,0,1,0
4,AAPL,2022-03-09,161.479996,162.949997,163.410004,159.410004,91454900,-0.532939,84,224,...,28.0,8.0,1.222222,33,0,0,Wednesday,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3663,WMT,2022-12-21,144.320007,145.179993,145.940002,144.259995,4575500,-1.058663,14,23,...,12.0,3.0,1.000000,21,0,0,Wednesday,0,0,1
3664,WMT,2022-12-22,144.770004,143.479996,144.979996,141.929993,4360800,-0.992514,9,33,...,14.0,3.0,1.111111,17,0,0,Thursday,1,0,0
3665,WMT,2022-12-27,144.039993,143.809998,144.449997,143.190002,3348200,-0.770568,19,25,...,5.0,5.0,1.250000,16,0,0,Tuesday,0,1,0
3666,WMT,2022-12-28,143.470001,141.289993,143.669998,140.910004,5082100,-0.819899,16,24,...,5.0,3.0,1.222222,17,0,0,Wednesday,0,0,1
3667,WMT,2022-12-29,142.139999,142.149994,143.020004,141.750000,3057300,-0.751577,11,20,...,3.0,2.0,1.400000,17,0,0,Thursday,1,0,0

In [194]:
df_final.to_csv('drive/My Drive/thesis/dataset/final_dataset_with_all_stock.csv [Final one]')

In [195]:
len(set(df_final.stock_symbol))

29

In [73]:
df = pd.read_csv('drive/My Drive/thesis/dataset/final_dataset_with_all_stock.csv [Final one]')

In [74]:
df = df.drop(df.columns[0],axis=1)

In [75]:
df

,stock_symbol,Date,Open,Close,High,Low,Volume,macd,tweet_sentiment_count_0,tweet_sentiment_count_1,...,Wednesday,tweet_0_pct,tweet_1_pct,tweet_2_pct,stocktwit_0_pct,stocktwit_1_pct,news_0_pct,news_1_pct,news_2_pct,stocktwit_2_pct
0,AAPL,2022-03-01,164.699997,163.199997,166.600006,161.970001,83474400,-0.760515,164,125,...,0,0.340956,0.259875,0.399168,0.617219,0.382781,0.666667,0.333333,0.000000,NaN
1,AAPL,2022-03-02,164.389999,166.559998,167.360001,162.949997,79724800,-0.470632,69,200,...,1,0.161972,0.469484,0.368545,0.734488,0.265512,1.000000,0.000000,0.000000,NaN
2,AAPL,2022-03-03,168.470001,166.229996,168.910004,165.550003,76678400,-0.274369,103,160,...,0,0.213251,0.331263,0.455487,0.660628,0.339372,0.000000,1.000000,0.000000,NaN
3,AAPL,2022-03-08,158.820007,157.440002,162.880005,155.800003,131148300,-0.797608,158,503,...,0,0.150907,0.480420,0.368672,0.637310,0.362690,0.021277,0.808511,0.170213,NaN
4,AAPL,2022-03-09,161.479996,162.949997,163.410004,159.410004,91454900,-0.532939,84,224,...,1,0.156716,0.417910,0.425373,0.740496,0.259504,0.000000,0.777778,0.222222,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3794,WMT,2022-12-21,144.320007,145.179993,145.940002,144.259995,4575500,-1.058663,14,23,...,1,0.186667,0.306667,0.506667,0.829268,0.170732,0.166667,0.666667,0.166667,NaN
3795,WMT,2022-12-22,144.770004,143.479996,144.979996,141.929993,4360800,-0.992514,9,33,...,0,0.105882,0.388235,0.505882,0.741935,0.258065,0.055556,0.777778,0.166667,NaN
3796,WMT,2022-12-27,144.039993,143.809998,144.449997,143.190002,3348200,-0.770568,19,25,...,0,0.250000,0.328947,0.421053,0.562500,0.437500,0.166667,0.416667,0.416667,NaN
3797,WMT,2022-12-28,143.470001,141.289993,143.669998,140.910004,5082100,-0.819899,16,24,...,1,0.200000,0.300000,0.500000,0.633333,0.366667,0.111111,0.555556,0.333333,NaN
3798,WMT,2022-12-29,142.139999,142.149994,143.020004,141.750000,3057300,-0.751577,11,20,...,0,0.166667,0.303030,0.530303,0.900000,0.100000,0.000000,0.600000,0.400000,NaN

In [76]:
df.columns

Index(['stock_symbol', 'Date', 'Open', 'Close', 'High', 'Low', 'Volume',
       'macd', 'tweet_sentiment_count_0', 'tweet_sentiment_count_1',
       'tweet_sentiment_count_2', 'tweet_sentiment_mean',
       'stocktwit_sentiment_count_0', 'stocktwit_sentiment_count_1',
       'stocktwit_sentiment_mean', 'news_sentiment_count_0',
       'news_sentiment_count_1', 'news_sentiment_count_2',
       'news_sentiment_mean', 'trends', 'Null_value_news',
       'Null_value_stocktwit', 'week_day', 'Thursday', 'Tuesday', 'Wednesday',
       'tweet_0_pct', 'tweet_1_pct', 'tweet_2_pct', 'stocktwit_0_pct',
       'stocktwit_1_pct', 'news_0_pct', 'news_1_pct', 'news_2_pct',
       'stocktwit_2_pct'],
      dtype='object')

In [77]:
df = df.rename(columns={'stocktwit_sentiment_count_0': 'stocktwit_sentiment_count_1', 'stocktwit_sentiment_count_1': 'stocktwit_sentiment_count_0'})

In [78]:
df = df.drop(['stocktwit_sentiment_mean'],axis=1)

In [79]:
df.columns

Index(['stock_symbol', 'Date', 'Open', 'Close', 'High', 'Low', 'Volume',
       'macd', 'tweet_sentiment_count_0', 'tweet_sentiment_count_1',
       'tweet_sentiment_count_2', 'tweet_sentiment_mean',
       'stocktwit_sentiment_count_1', 'stocktwit_sentiment_count_0',
       'news_sentiment_count_0', 'news_sentiment_count_1',
       'news_sentiment_count_2', 'news_sentiment_mean', 'trends',
       'Null_value_news', 'Null_value_stocktwit', 'week_day', 'Thursday',
       'Tuesday', 'Wednesday', 'tweet_0_pct', 'tweet_1_pct', 'tweet_2_pct',
       'stocktwit_0_pct', 'stocktwit_1_pct', 'news_0_pct', 'news_1_pct',
       'news_2_pct', 'stocktwit_2_pct'],
      dtype='object')

In [80]:
df['stocktwit_sentiment_mean'] = (df['stocktwit_sentiment_count_0']*0 + df['stocktwit_sentiment_count_1']*1) / (df['stocktwit_sentiment_count_0'] + df['stocktwit_sentiment_count_1'])

In [81]:
df.columns

Index(['stock_symbol', 'Date', 'Open', 'Close', 'High', 'Low', 'Volume',
       'macd', 'tweet_sentiment_count_0', 'tweet_sentiment_count_1',
       'tweet_sentiment_count_2', 'tweet_sentiment_mean',
       'stocktwit_sentiment_count_1', 'stocktwit_sentiment_count_0',
       'news_sentiment_count_0', 'news_sentiment_count_1',
       'news_sentiment_count_2', 'news_sentiment_mean', 'trends',
       'Null_value_news', 'Null_value_stocktwit', 'week_day', 'Thursday',
       'Tuesday', 'Wednesday', 'tweet_0_pct', 'tweet_1_pct', 'tweet_2_pct',
       'stocktwit_0_pct', 'stocktwit_1_pct', 'news_0_pct', 'news_1_pct',
       'news_2_pct', 'stocktwit_2_pct', 'stocktwit_sentiment_mean'],
      dtype='object')

In [82]:
df_final = df[['stock_symbol', 'Date', 'Open', 'Close', 'High', 'Low', 'Volume',
       'macd', 'tweet_sentiment_count_0', 'tweet_sentiment_count_1',
       'tweet_sentiment_count_2', 'tweet_sentiment_mean',
       'stocktwit_sentiment_count_0', 'stocktwit_sentiment_count_1', 'stocktwit_sentiment_mean',
       'news_sentiment_count_0', 'news_sentiment_count_1',
       'news_sentiment_count_2', 'news_sentiment_mean', 'trends',
       'Null_value_news', 'Null_value_stocktwit', 'week_day', 'Thursday',
       'Tuesday', 'Wednesday']].copy()

In [83]:
df_final['tweet_0_pct'] = df_final['tweet_sentiment_count_0'] / (df_final['tweet_sentiment_count_0'] + df_final['tweet_sentiment_count_1'] + df_final['tweet_sentiment_count_2'])
df_final['tweet_1_pct'] = df_final['tweet_sentiment_count_1'] / (df_final['tweet_sentiment_count_0'] + df_final['tweet_sentiment_count_1'] + df_final['tweet_sentiment_count_2'])
df_final['tweet_2_pct'] = df_final['tweet_sentiment_count_2'] / (df_final['tweet_sentiment_count_0'] + df_final['tweet_sentiment_count_1'] + df_final['tweet_sentiment_count_2'])

In [84]:
df_final['stocktwit_0_pct'] = df_final['stocktwit_sentiment_count_0'] / (df_final['stocktwit_sentiment_count_0'] + df_final['stocktwit_sentiment_count_1'])
df_final['stocktwit_1_pct'] = df_final['stocktwit_sentiment_count_1'] / (df_final['stocktwit_sentiment_count_0'] + df_final['stocktwit_sentiment_count_1'])

In [85]:
df_final['news_0_pct'] = df_final['news_sentiment_count_0'] / (df_final['news_sentiment_count_0'] + df_final['news_sentiment_count_1'] + df_final['news_sentiment_count_2'])
df_final['news_1_pct'] = df_final['news_sentiment_count_1'] / (df_final['news_sentiment_count_0'] + df_final['news_sentiment_count_1'] + df_final['news_sentiment_count_2'])
df_final['news_2_pct'] = df_final['news_sentiment_count_2'] / (df_final['news_sentiment_count_0'] + df_final['news_sentiment_count_1'] + df_final['news_sentiment_count_2'])

In [86]:
df_final

,stock_symbol,Date,Open,Close,High,Low,Volume,macd,tweet_sentiment_count_0,tweet_sentiment_count_1,...,Tuesday,Wednesday,tweet_0_pct,tweet_1_pct,tweet_2_pct,stocktwit_0_pct,stocktwit_1_pct,news_0_pct,news_1_pct,news_2_pct
0,AAPL,2022-03-01,164.699997,163.199997,166.600006,161.970001,83474400,-0.760515,164,125,...,1,0,0.340956,0.259875,0.399168,0.382781,0.617219,0.666667,0.333333,0.000000
1,AAPL,2022-03-02,164.389999,166.559998,167.360001,162.949997,79724800,-0.470632,69,200,...,0,1,0.161972,0.469484,0.368545,0.265512,0.734488,1.000000,0.000000,0.000000
2,AAPL,2022-03-03,168.470001,166.229996,168.910004,165.550003,76678400,-0.274369,103,160,...,0,0,0.213251,0.331263,0.455487,0.339372,0.660628,0.000000,1.000000,0.000000
3,AAPL,2022-03-08,158.820007,157.440002,162.880005,155.800003,131148300,-0.797608,158,503,...,1,0,0.150907,0.480420,0.368672,0.362690,0.637310,0.021277,0.808511,0.170213
4,AAPL,2022-03-09,161.479996,162.949997,163.410004,159.410004,91454900,-0.532939,84,224,...,0,1,0.156716,0.417910,0.425373,0.259504,0.740496,0.000000,0.777778,0.222222
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3794,WMT,2022-12-21,144.320007,145.179993,145.940002,144.259995,4575500,-1.058663,14,23,...,0,1,0.186667,0.306667,0.506667,0.170732,0.829268,0.166667,0.666667,0.166667
3795,WMT,2022-12-22,144.770004,143.479996,144.979996,141.929993,4360800,-0.992514,9,33,...,0,0,0.105882,0.388235,0.505882,0.258065,0.741935,0.055556,0.777778,0.166667
3796,WMT,2022-12-27,144.039993,143.809998,144.449997,143.190002,3348200,-0.770568,19,25,...,1,0,0.250000,0.328947,0.421053,0.437500,0.562500,0.166667,0.416667,0.416667
3797,WMT,2022-12-28,143.470001,141.289993,143.669998,140.910004,5082100,-0.819899,16,24,...,0,1,0.200000,0.300000,0.500000,0.366667,0.633333,0.111111,0.555556,0.333333
3798,WMT,2022-12-29,142.139999,142.149994,143.020004,141.750000,3057300,-0.751577,11,20,...,0,0,0.166667,0.303030,0.530303,0.100000,0.900000,0.000000,0.600000,0.400000

In [87]:
df_final.loc[df_final["stocktwit_sentiment_mean"].isnull(), "stocktwit_sentiment_mean"] = 0.5

In [88]:
df_final.loc[df_final["stocktwit_0_pct"].isnull(), "stocktwit_0_pct"] = 0
df_final.loc[df_final["stocktwit_1_pct"].isnull(), "stocktwit_1_pct"] = 0
df_final.loc[df_final["news_0_pct"].isnull(), "news_0_pct"] = 0
df_final.loc[df_final["news_1_pct"].isnull(), "news_1_pct"] = 0
df_final.loc[df_final["news_2_pct"].isnull(), "news_2_pct"] = 0

In [89]:
df_final.to_csv('drive/My Drive/thesis/dataset/final_dataset_with_all_stock.csv [Final one]')